### ISSUE TITLE
Test with WordPress 5.9

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/otter-blocks#657]
Hey @irinelenache, can you help with testing the Otter with WordPress 5.9's latest beta when you have some free time? You can list any issues that you find (including styling issues) here.

Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani Tested with Wordpress 5.9 RC 1 and found 2 small things:

- [ ] The popup block doesn't work in frontend and when i want to edit the post, the editor is not loading and i get an error in console https://vertis.d.pr/UWe2U4
- [ ] For the Comparison table, alternating row color doesn't work with the default color (rest of them work fine)
editor: https://vertis.d.pr/28Z2O9
frontend: https://vertis.d.pr/IbGFBP

**Comment by HardeepAsrani** [comment]
@irinelenache Any idea if these issues are still there? https://github.com/Codeinwp/otter-blocks/issues/573

**Comment by HardeepAsrani** [comment]
@irinelenache 

- Popup issue was fixed here: https://github.com/Codeinwp/otter-blocks/pull/684
- I can't seem to reproduce it. It's working fine for me. Are you using any particular browser?

Apart from these, anything else? Also see the last comment. Thanks!

**Comment by irinelenache** [comment]
@HardeepAsrani 
- The issues regarding the Gallery block are still there
- The popup issue is fixed, thank you 🚀 
- For the comparison block issue, i created a video for it https://vertis.d.pr/EO5YuS . I'm using Chrome, but the issue persists on frontend on Browserstack too

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you take care of 5.9 issues?

**Comment by Soare-Robert-Daniel** [comment]
> * The issues regarding the Gallery block are still there

@irinelenache, what are the issues with the Gallery?

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache can you check if the Neve Pro CSS files are loading for you with this https://github.com/Codeinwp/neve-pro-addon/pull/1818 ?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, we got a problem with Neve Pro Addon. It is not loading the CSS file for the Table Comparison.

@cristian-ungureanu, any idea of some condition that blocks the CSS files loading?

**Comment by cristian-ungureanu** [comment]
@Soare-Robert-Daniel https://github.com/Codeinwp/neve-pro-addon/blob/master/includes/modules/woocommerce_booster/comparison_table/main.php#L159-L161

@mskapusuz can you have a look here?

**Comment by mskapusuz** [comment]
@cristian-ungureanu @Soare-Robert-Daniel 

there is a condition for loading dynamic styles on here: https://github.com/Codeinwp/neve-pro-addon/blob/master/includes/modules/woocommerce_booster/dynamic_style.php#L95-L106

**Comment by Soare-Robert-Daniel** [comment]
@cristian-ungureanu this is what I got from the debugger from that line.
![image](https://user-images.githubusercontent.com/17597852/150311934-2d738730-0f4b-40bf-9e7d-a6f574e39905.png)

@mskapusuz that function works fine

https://user-images.githubusercontent.com/17597852/150311971-9417f3b4-5ed5-4740-a204-1dbe75678102.mp4

**Comment by mskapusuz** [comment]
@Soare-Robert-Daniel 

if [this condition](https://github.com/Codeinwp/neve-pro-addon/blob/master/includes/modules/woocommerce_booster/comparison_table/main.php#L159) caused the return false on L160, you can manage it from [here](https://github.com/Codeinwp/neve-pro-addon/blob/80cedabcc93ecee7ca9ccd18df94f51d4da7dee3/includes/modules/woocommerce_booster/comparison_table/view/table.php#L317-L333)

Also did you try to remove the condition on [here](https://github.com/Codeinwp/neve-pro-addon/blob/master/includes/modules/woocommerce_booster/comparison_table/main.php#L159-L161) during the debugging? is everything works well when you remove the condition? 

If you need help, we can make a slack call on tomorrow?

**Comment by Soare-Robert-Daniel** [comment]
> Also did you try to remove the condition on [here](https://github.com/Codeinwp/neve-pro-addon/blob/master/includes/modules/woocommerce_booster/comparison_table/main.php#L159-L161) during the debugging? is everything works well when you remove the condition?

No, I did not. From looking at the mentioned lines, in [this part of the code](https://github.com/Codeinwp/neve-pro-addon/blob/80cedabcc93ecee7ca9ccd18df94f51d4da7dee3/includes/modules/woocommerce_booster/comparison_table/view/table.php#L317-L333), the otter block detection is missing. It needs to be like [this](https://github.com/Codeinwp/neve-pro-addon/blob/master/includes/modules/woocommerce_booster/dynamic_style.php#L95-L106) with `has_comparison_block` condition.

> If you need help, we can make a slack call on tomorrow?

We can do that if that is the case.

**Comment by mskapusuz** [comment]
@Soare-Robert-Daniel 

to be consistent with https://github.com/Codeinwp/neve-pro-addon/blob/master/includes/modules/woocommerce_booster/dynamic_style.php#L95-L106

I'll made a PR on Neve Pro then let you know

**Comment by mskapusuz** [comment]
@Soare-Robert-Daniel the [PR](https://github.com/Codeinwp/neve-pro-addon/pull/1834)? is ready on Neve Pro side. can you test it?

**Comment by irinelenache** [comment]
@mskapusuz @Soare-Robert-Daniel I tested the comparison table with [the PR](https://github.com/Codeinwp/neve-pro-addon/pull/1834) provided by Mustafa and it looks ok in frontend, but not all colors are rendering in editor https://vertis.d.pr/GY5GOf

**Comment by mskapusuz** [comment]
update: @Soare-Robert-Daniel as I see, the problem comes from the Neve side. The dynamic styles are not loaded for .nv-ct-container on editor side

I'll handle that and let you know

**Comment by mskapusuz** [comment]
@Soare-Robert-Daniel @irinelenache 

The issue has been fixed on Neve Pro and Otter Block sides. To able to fix the issue: both of the mentioned PRs must be released.

Thanks!

### Test instructions
Install Otter from this PR: https://github.com/Codeinwp/otter-blocks/pull/691
Install Neve Pro from this PR: [fix: comparison table/otter blocks compatibility neve-pro-addon#1834](https://github.com/Codeinwp/neve-pro-addon/pull/1834)

**Expected case:** Comparison Table block should be worked well on frontend+editor side.

**Comment by irinelenache** [comment]
@mskapusuz Tested again and now the Comparison block works fine both in editor and frontend 🚀 I think it can be merged when @Soare-Robert-Daniel better checks the Otter PR 👍
